apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: prod-issuer
  namespace: ghost
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: service-key
      key: key
